#include <game/attack_simulator.hpp>
#include <game/unit_names.hpp>

std::map<std::tuple<std::string, std::string>, AttackSimulator::DamageValues> AttackSimulator::damage_table{

    // ANTIAIR
    {{ANTIAIR, ANTIAIR}, {45, {}}},
    {{ANTIAIR, APC}, {50, {}}},
    {{ANTIAIR, ARTILLERY}, {50, {}}},
    {{ANTIAIR, BATTLECOPTER}, {120, {}}},
    {{ANTIAIR, BOMBER}, {75, {}}},
    {{ANTIAIR, FIGHTER}, {65, {}}},
    {{ANTIAIR, INFANTRY}, {105, {}}},
    {{ANTIAIR, MEDIUMTANK}, {10, {}}},
    {{ANTIAIR, MECH}, {105, {}}},
    {{ANTIAIR, MEGATANK}, {105, {}}},
    {{ANTIAIR, MISSILE}, {55, {}}},
    {{ANTIAIR, NEOTANK}, {5, {}}},
    {{ANTIAIR, PIPERUNNER}, {25, {}}},
    {{ANTIAIR, RECON}, {60, {}}},
    {{ANTIAIR, ROCKET}, {55, {}}},
    {{ANTIAIR, STEALTH}, {75, {}}},
    {{ANTIAIR, TCOPTER}, {120, {}}},
    {{ANTIAIR, TANK}, {120, {}}},

    // APC
    // ARTILLERY
    {{ARTILLERY, ANTIAIR}, {75, {}}},
    {{ARTILLERY, APC}, {70, {}}},
    {{ARTILLERY, ARTILLERY}, {75, {}}},
    {{ARTILLERY, BATTLESHIP}, {40, {}}},
    {{ARTILLERY, BLACKBOAT}, {55, {}}},
    {{ARTILLERY, CARRIER}, {45, {}}},
    {{ARTILLERY, BATTLESHIP}, {65, {}}},
    {{ARTILLERY, INFANTRY}, {90, {}}},
    {{ARTILLERY, LANDER}, {55, {}}},
    {{ARTILLERY, MEDIUMTANK}, {45, {}}},
    {{ARTILLERY, MECH}, {85, {}}},
    {{ARTILLERY, MEGATANK}, {15, {}}},
    {{ARTILLERY, MISSILE}, {80, {}}},
    {{ARTILLERY, NEOTANK}, {40, {}}},
    {{ARTILLERY, PIPERUNNER}, {70, {}}},
    {{ARTILLERY, RECON}, {80, {}}},
    {{ARTILLERY, ROCKET}, {80, {}}},
    {{ARTILLERY, SUB}, {60, {}}},
    {{ARTILLERY, TANK}, {70, {}}},
    // BATTLECOPTER

    {{BATTLECOPTER, ANTIAIR}, {25, 6}},
    {{BATTLECOPTER, APC}, {60, 20}},
    {{BATTLECOPTER, ARTILLERY}, {65, 25}},
    {{BATTLECOPTER, BATTLECOPTER}, {{}, 65}},
    {{BATTLECOPTER, BATTLESHIP}, {25, {}}},
    {{BATTLECOPTER, BLACKBOAT}, {25, {}}},
    {{BATTLECOPTER, CARRIER}, {25, {}}},
    {{BATTLECOPTER, CRUISER}, {55, {}}},
    {{BATTLECOPTER, INFANTRY}, {{}, 75}},
    {{BATTLECOPTER, LANDER}, {25, {}}},
    {{BATTLECOPTER, MEDIUMTANK}, {25, 1}},
    {{BATTLECOPTER, MECH}, {{}, 75}},
    {{BATTLECOPTER, MEGATANK}, {10, 1}},
    {{BATTLECOPTER, MISSILE}, {65, 35}},
    {{BATTLECOPTER, NEOTANK}, {20, 1}},
    {{BATTLECOPTER, PIPERUNNER}, {55, 6}},
    {{BATTLECOPTER, RECON}, {55, 30}},
    {{BATTLECOPTER, ROCKET}, {65, 35}},
    {{BATTLECOPTER, SUB}, {25, {}}},
    {{BATTLECOPTER, TCOPTER}, {{}, 95}},
    {{BATTLECOPTER, TANK}, {55, 6}},
    // BATTLESHIP
    {{BATTLESHIP, ANTIAIR}, {85, {}}},
    {{BATTLESHIP, APC}, {80, {}}},
    {{BATTLESHIP, ARTILLERY}, {80, {}}},
    {{BATTLESHIP, BATTLESHIP}, {50, {}}},
    {{BATTLESHIP, BLACKBOAT}, {95, {}}},
    {{BATTLESHIP, CARRIER}, {60, {}}},
    {{BATTLESHIP, CRUISER}, {95, {}}},
    {{BATTLESHIP, INFANTRY}, {95, {}}},
    {{BATTLESHIP, LANDER}, {95, {}}},
    {{BATTLESHIP, MEDIUMTANK}, {55, {}}},
    {{BATTLESHIP, MECH}, {90, {}}},
    {{BATTLESHIP, MEGATANK}, {25, {}}},
    {{BATTLESHIP, MISSILE}, {90, {}}},
    {{BATTLESHIP, NEOTANK}, {50, {}}},
    {{BATTLESHIP, PIPERUNNER}, {80, {}}},
    {{BATTLESHIP, RECON}, {90, {}}},
    {{BATTLESHIP, ROCKET}, {85, {}}},
    {{BATTLESHIP, SUB}, {95, {}}},
    {{BATTLESHIP, TANK}, {80, {}}},

    // BLACKBOAT
    // BOMBER
    {{BOMBER, ANTIAIR}, {95, {}}},
    {{BOMBER, APC}, {105, {}}},
    {{BOMBER, ARTILLERY}, {105, {}}},
    {{BOMBER, BATTLESHIP}, {75, {}}},
    {{BOMBER, BLACKBOAT}, {95, {}}},
    {{BOMBER, CARRIER}, {75, {}}},
    {{BOMBER, CRUISER}, {85, {}}},
    {{BOMBER, INFANTRY}, {110, {}}},
    {{BOMBER, BLACKBOAT}, {95, {}}},
    {{BOMBER, MEDIUMTANK}, {95, {}}},
    {{BOMBER, MECH}, {110, {}}},
    {{BOMBER, MEGATANK}, {35, {}}},
    {{BOMBER, MISSILE}, {105, {}}},
    {{BOMBER, NEOTANK}, {90, {}}},
    {{BOMBER, PIPERUNNER}, {105, {}}},
    {{BOMBER, RECON}, {105, {}}},
    {{BOMBER, MISSILE}, {105, {}}},
    {{BOMBER, SUB}, {95, {}}},
    {{BOMBER, TANK}, {105, {}}},
    // CARRIER
    {{CARRIER, BATTLECOPTER}, {115, {}}},
    {{CARRIER, BOMBER}, {100, {}}},
    {{CARRIER, FIGHTER}, {100, {}}},
    {{CARRIER, STEALTH}, {100, {}}},
    {{CARRIER, TCOPTER}, {115, {}}},
    // CRUISER
    {{CRUISER, BATTLECOPTER}, {{}, 115}},
    {{CRUISER, BLACKBOAT}, {25, {}}},
    {{CRUISER, BOMBER}, {{}, 65}},
    {{CRUISER, CARRIER}, {5, {}}},
    {{CRUISER, FIGHTER}, {{}, 55}},
    {{CRUISER, STEALTH}, {{}, 55}},
    {{CRUISER, SUB}, {90, {}}},
    {{CRUISER, TCOPTER}, {{}, 115}},
    // FIGHTER
    {{FIGHTER, BATTLECOPTER}, {100, {}}},
    {{FIGHTER, BOMBER}, {100, {}}},
    {{FIGHTER, FIGHTER}, {55, {}}},
    {{FIGHTER, STEALTH}, {85, {}}},
    {{FIGHTER, TCOPTER}, {100, {}}},

    // INFANTRY
    {{INFANTRY, ANTIAIR}, {{}, 5}},
    {{INFANTRY, APC}, {{}, 12}},
    {{INFANTRY, ARTILLERY}, {{}, 15}},
    {{INFANTRY, BATTLECOPTER}, {{}, 7}},
    {{INFANTRY, INFANTRY}, {{}, 55}},
    {{INFANTRY, MEDIUMTANK}, {{}, 1}},
    {{INFANTRY, MECH}, {{}, 45}},
    {{INFANTRY, MEGATANK}, {{}, 1}},
    {{INFANTRY, MISSILE}, {{}, 26}},
    {{INFANTRY, NEOTANK}, {{}, 1}},
    {{INFANTRY, PIPERUNNER}, {{}, 5}},
    {{INFANTRY, RECON}, {{}, 12}},
    {{INFANTRY, ROCKET}, {{}, 25}},
    {{INFANTRY, TCOPTER}, {{}, 30}},
    {{INFANTRY, TANK}, {{}, 5}},
    // LANDER
    // MEDIUMTANK
    {{MEDIUMTANK, ANTIAIR}, {105, 7}},
    {{MEDIUMTANK, APC}, {105, 45}},
    {{MEDIUMTANK, ARTILLERY}, {105, 45}},
    {{MEDIUMTANK, BATTLECOPTER}, {{}, 12}},
    {{MEDIUMTANK, BATTLESHIP}, {10, {}}},
    {{MEDIUMTANK, BLACKBOAT}, {35, {}}},
    {{MEDIUMTANK, CARRIER}, {10, {}}},
    {{MEDIUMTANK, CRUISER}, {45, {}}},
    {{MEDIUMTANK, INFANTRY}, {{}, 105}},
    {{MEDIUMTANK, LANDER}, {35, {}}},
    {{MEDIUMTANK, MEDIUMTANK}, {55, 1}},
    {{MEDIUMTANK, MECH}, {{}, 95}},
    {{MEDIUMTANK, MEGATANK}, {25, 1}},
    {{MEDIUMTANK, MISSILE}, {105, 35}},
    {{MEDIUMTANK, NEOTANK}, {45, 1}},
    {{MEDIUMTANK, PIPERUNNER}, {85, 8}},
    {{MEDIUMTANK, RECON}, {105, 45}},
    {{MEDIUMTANK, ROCKET}, {105, 45}},
    {{MEDIUMTANK, SUB}, {10, {}}},
    {{MEDIUMTANK, TCOPTER}, {{}, 45}},
    {{MEDIUMTANK, TANK}, {85, 8}},
    // MECH
    {{MECH, ANTIAIR}, {65, 6}},
    {{MECH, APC}, {75, 20}},
    {{MECH, ARTILLERY}, {70, 32}},
    {{MECH, BATTLECOPTER}, {9, 9}},
    {{MECH, INFANTRY}, {{}, 65}},
    {{MECH, MEDIUMTANK}, {15, 1}},
    {{MECH, MECH}, {{}, 55}},
    {{MECH, MEGATANK}, {5, 1}},
    {{MECH, MISSILE}, {85, 35}},
    {{MECH, NEOTANK}, {15, 1}},
    {{MECH, PIPERUNNER}, {55, 6}},
    {{MECH, RECON}, {85, 18}},
    {{MECH, ROCKET}, {85, 35}},
    {{MECH, TCOPTER}, {{}, 35}},
    {{MECH, TANK}, {55, 6}},
    // MEGATANK
    {{MEGATANK, ANTIAIR}, {195, 17}},
    {{MEGATANK, APC}, {195, 65}},
    {{MEGATANK, ARTILLERY}, {195, 65}},
    {{MEGATANK, BATTLECOPTER}, {{}, 22}},
    {{MEGATANK, BATTLESHIP}, {45, {}}},
    {{MEGATANK, BLACKBOAT}, {105, {}}},
    {{MEGATANK, CARRIER}, {45, {}}},
    {{MEGATANK, CRUISER}, {65, {}}},
    {{MEGATANK, INFANTRY}, {{}, 135}},
    {{MEGATANK, LANDER}, {75, {}}},
    {{MEGATANK, MEDIUMTANK}, {125, 1}},
    {{MEGATANK, MECH}, {{}, 125}},
    {{MEGATANK, MEGATANK}, {65, 1}},
    {{MEGATANK, MISSILE}, {195, 55}},
    {{MEGATANK, NEOTANK}, {115, 1}},
    {{MEGATANK, PIPERUNNER}, {180, 10}},
    {{MEGATANK, RECON}, {195, 65}},
    {{MEGATANK, ROCKET}, {195, 75}},
    {{MEGATANK, SUB}, {45, {}}},
    {{MEGATANK, TCOPTER}, {{}, 55}},
    {{MEGATANK, TANK}, {180, 10}},
    // MISSILE

    {{MISSILE, BATTLECOPTER}, {120, {}}},
    {{MISSILE, BOMBER}, {100, {}}},
    {{MISSILE, FIGHTER}, {100, {}}},
    {{MISSILE, STEALTH}, {100, {}}},
    {{MISSILE, TCOPTER}, {120, {}}},

// NEOTANK
    {{NEOTANK, ANTIAIR}, {115, 17}},
    {{NEOTANK, APC}, {125, 65}},
    {{NEOTANK, ARTILLERY}, {115, 65}},
    {{NEOTANK, BATTLECOPTER}, {{}, 22}},
    {{NEOTANK, BATTLESHIP}, {15, {}}},
    {{NEOTANK, BLACKBOAT}, {40, {}}},
    {{NEOTANK, CARRIER}, {15, {}}},
    {{NEOTANK, CRUISER}, {50, {}}},
    {{NEOTANK, INFANTRY}, {{}, 125}},
    {{NEOTANK, LANDER}, {50, {}}},
    {{NEOTANK, MEDIUMTANK}, {75, 1}},
    {{NEOTANK, MECH}, {{}, 115}},
    {{NEOTANK, MEGATANK}, {35, 1}},
    {{NEOTANK, MISSILE}, {125, 55}},
    {{NEOTANK, NEOTANK}, {55, 1}},
    {{NEOTANK, PIPERUNNER}, {105, 10}},
    {{NEOTANK, RECON}, {125, 65}},
    {{NEOTANK, ROCKET}, {125, 75}},
    {{NEOTANK, SUB}, {15, {}}},
    {{NEOTANK, TCOPTER}, {{}, 55}},
    {{NEOTANK, TANK}, { 105, 10 }},
    // PIPERUNNER
    {{PIPERUNNER, ANTIAIR}, { 85, {}}},
    {{PIPERUNNER, APC}, { 80, {}} },
    {{PIPERUNNER, ARTILLERY}, { 80, {} }},
    {{PIPERUNNER, BATTLECOPTER}, { 105,{} }},
    {{PIPERUNNER, BATTLESHIP}, { 55,{} }},
    {{PIPERUNNER, BLACKBOAT}, { 60,{} }},
    {{PIPERUNNER, BOMBER}, { 75,{} }},
    {{PIPERUNNER, CARRIER}, { 60,{} }},
    {{PIPERUNNER, CRUISER}, { 85,{} }},
    {{PIPERUNNER, FIGHTER}, { 65,{} }},
    {{PIPERUNNER, INFANTRY}, { 95,{} }},
    {{PIPERUNNER, LANDER}, { 60,{} }},
    {{PIPERUNNER, MEDIUMTANK}, { 55,{} }},
    {{PIPERUNNER, MECH}, { 90,{} }},
    {{PIPERUNNER, MEGATANK}, { 25,{} }},
    {{PIPERUNNER, MISSILE}, { 90,{} }},
    {{PIPERUNNER, NEOTANK}, { 50,{} }},
    {{PIPERUNNER, PIPERUNNER}, { 80,{} }},
    {{PIPERUNNER, RECON}, { 90,{} }},
    {{PIPERUNNER, ROCKET}, { 85,{} }},
    {{PIPERUNNER, STEALTH}, { 75,{} }},
    {{PIPERUNNER, SUB}, { 85,{} }},
    {{PIPERUNNER, TCOPTER}, { 105,{} }},
    {{PIPERUNNER, TANK}, { 80,{} }},
// RECON
    {{RECON, ANTIAIR}, { {},4 }},
    {{RECON, APC}, { {},45 }},
    {{RECON, ARTILLERY}, { {},45 }},
    {{RECON, BATTLECOPTER}, { {},12 }},
    {{RECON, INFANTRY}, { {},70 }},
    {{RECON, MEDIUMTANK}, { {},1 }},
    {{RECON, MECH}, { {},65 }},
    {{RECON, MEGATANK}, { {},1 }},
    {{RECON, MISSILE}, { {},28 }},
    {{RECON, NEOTANK}, { {},1 }},
    {{RECON, PIPERUNNER}, { {},6 }},
    {{RECON, RECON}, { {},35 }},
    {{RECON, ROCKET}, { {},55 }},
    {{RECON, TCOPTER}, { {},35 }},
    {{RECON, TANK}, { {},6 }},
// MISSILE
    {{RECON, ANTIAIR}, { 85,{} }},
    {{RECON, APC}, { 80,{} }},
    {{RECON, ARTILLERY}, { 80,{} }},
    {{RECON, BATTLESHIP}, { 55,{} }},
    {{RECON, BLACKBOAT}, { 60,{} }},
    {{RECON, CARRIER}, { 60,{} }},
    {{RECON, CRUISER}, { 85,{} }},
    {{RECON, INFANTRY}, { 95,{} }},
    {{RECON, LANDER}, { 60,{} }},
    {{RECON, MEDIUMTANK}, { 55,{} }},
    {{RECON, MECH}, { 90,{} }},
    {{RECON, MEGATANK}, { 25,{} }},
    {{RECON, MISSILE}, { 90,{} }},
    {{RECON, NEOTANK}, { 50,{} }},
    {{RECON, PIPERUNNER}, { 80,{} }},
    {{RECON, RECON}, { 90,{} }},
    {{RECON, ROCKET}, { 85,{} }},
    {{RECON, SUB}, { 85,{} }},
    {{RECON, TANK}, { 80,{} }},
// STEALTH
    {{STEALTH, ANTIAIR }, { 50,{} }},
    {{STEALTH, APC }, { 85,{} }},
    {{STEALTH, ARTILLERY }, { 75,{} }},
    {{STEALTH, BATTLECOPTER }, { 85,{} }},
    {{STEALTH, BATTLESHIP }, { 45,{} }},
    {{STEALTH, BLACKBOAT }, { 65,{} }},
    {{STEALTH, BOMBER }, { 70,{} }},
    {{STEALTH, CARRIER }, { 45,{} }},
    {{STEALTH, CRUISER }, { 35,{} }},
    {{STEALTH, FIGHTER }, { 45,{} }},
    {{STEALTH, INFANTRY }, { 90,{} }},
    {{STEALTH, LANDER }, { 65,{} }},
    {{STEALTH, MEDIUMTANK }, { 70,{} }},
    {{STEALTH, MECH }, { 90,{} }},
    {{STEALTH, MEGATANK }, { 15,{} }},
    {{STEALTH, MISSILE }, { 85,{} }},
    {{STEALTH, NEOTANK }, { 60,{} }},
    {{STEALTH, PIPERUNNER }, { 80,{} }},
    {{STEALTH, RECON }, { 85,{} }},
    {{STEALTH, ROCKET}, { 85,{} }},
    {{STEALTH, STEALTH}, { 55,{} }},
    {{STEALTH, SUB}, { 55,{} }},
    {{STEALTH, TCOPTER}, { 95,{} }},
    {{STEALTH, TANK}, { 75,{} }},
// SUB
    {{SUB, BATTLESHIP}, { 55,{} }},
    {{SUB, BLACKBOAT}, { 95,{} }},
    {{SUB, CARRIER}, { 75,{} }},
    {{SUB, CRUISER}, { 25,{} }},
    {{SUB, LANDER}, { 95,{} }},
    {{SUB, SUB}, { 55,{} }},
// TCOPTER
    // TANK
    {{TANK, ANTIAIR}, {65, 5}},
    {{TANK, APC}, {75, 54}},
    {{TANK, ARTILLERY}, {70, 45}},
    {{TANK, BATTLECOPTER}, {{}, 10}},
    {{TANK, BATTLESHIP}, {1, {}}},
    {{TANK, BLACKBOAT}, {10, {}}},
    {{TANK, CARRIER}, {1, {}}},
    {{TANK, CRUISER}, {5, {}}},
    {{TANK, INFANTRY}, {{}, 75}},
    {{TANK, LANDER}, {10, {}}},
    {{TANK, MEDIUMTANK}, {15, 1}},
    {{TANK, MECH}, {{}, 70}},
    {{TANK, MEGATANK}, {10, 1}},
    {{TANK, MISSILE}, {85, 30}},
    {{TANK, NEOTANK}, {15, 1}},
    {{TANK, PIPERUNNER}, {55, 6}},
    {{TANK, RECON}, {85, 40}},
    {{TANK, ROCKET}, {85, 55}},
    {{TANK, SUB}, {1, {}}},
    {{TANK, TCOPTER}, {{}, 40}},
    {{TANK, TANK}, { 55, 6 }}
};